const SEARCH = "SEARCH";
const CHARGE_MAINPAGE = "CHARGE_MAINPAGE";
const SEARCH_ABILITY = "SEARCH_ABILITY";
const SEARCH_NAME_OR_ID = "SEARCH_NAME_OR_ID"

export { SEARCH, CHARGE_MAINPAGE, SEARCH_ABILITY, SEARCH_NAME_OR_ID };
